---
- name: Check traefik version
  shell: traefik version | grep 'Version:' | awk '{print $2}'
  args:
    executable: /bin/bash
  ignore_errors: true
  changed_when: false
  register: traefik_installed_version

- name: Check that the "{{ traefik_config_file }}" exists
  stat:
    path: "{{ traefik_config_file }}"
  register: traefik_stat_config
