---
- name: Check traefik version
  shell: traefik version | grep 'Version:' | awk '{print $2}'
  args:
    executable: /bin/bash
  ignore_errors: yes
  changed_when: false
  register: traefikInstalledVersion

- name: Check that the "{{ traefikConfigFile }}" exists
  stat:
    path: "{{ traefikConfigFile }}"
  register: traefikStat
