---
- name: Restart traefik
  systemd:
    name: traefik
    state: restarted

- name: Bind traefik
  shell: setcap 'cap_net_bind_service=+ep' {{ binDirectory }}/traefik
  args:
    executable: /bin/bash
