---
- name: Restart traefik
  systemd:
    name: traefik.service
    state: restarted

- name: Enable traefik
  systemd:
    name: traefik.service
    enabled: true

- name: Bind traefik
  command: setcap 'cap_net_bind_service=+ep' {{ traefik_bin_directory }}/traefik
