---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint

platforms:
  - name: "instance-docker-${MOLECULE_DISTRO:-debian10}-ansible-${GITHUB_JOB:-local}"
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian10}-ansible:${MOLECULE_DISTRO_TAG:-latest}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible

scenario:
  name: default
  idempotent: true
  test_sequence:
    - lint
    - destroy
    - create
    - converge
    - idempotence
    - destroy


verifier:
  name: ansible
